version: "2"

linters:
  default: standard
  enable:
    - maxcomments
  settings:
    custom:
      maxcomments:
        type: module
        description: Limits the number of comment lines per function and per file.
        original-url: github.com/samgozman/maxcomments-lint
        settings:
          max-func-lines: 15
          max-file-lines: 150
          ignore:
            - 'testdata/'
